[book]
authors = ["vinsiny"]
language = "zh-CN"
multilingual = false
src = "src"
title = "前端小册"

[build]
extra-watch-dirs = ['./README.md']

[output.html]
# theme = "my-theme"
# default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/vinsiny/fe-booklet"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/vinsiny/fe-booklet/edit/main/guide/{path}"
# site-url = "/example-book/"
# cname = "myproject.rs"
input-404 = "404.md"

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 1         # the depth to start folding